name: ViaCEP CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-report-via-cep
          path: reports/test-report-via-cep.html |
            dist
            !dist/**/*.md
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-report-via-cep
          path: |
            dist
            !dist/**/*.md
    outputs:
      artifact-id: ${{ github.run_id }}
      artifact-url: https://github.com/rubiperucci/sq3-section-a/actions/runs/${{ github.run_attempt }}/artifacts/${{ github.run_id }}